"""Добавлены комментарии к полям таблиц БД

Revision ID: 661a499dc48a
Revises: 3d61603d9b72
Create Date: 2026-01-16 17:56:38.265331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661a499dc48a'
down_revision: Union[str, Sequence[str], None] = '3d61603d9b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
