"""Инициализация БД

Revision ID: c27e1cbe927d
Revises: 
Create Date: 2026-01-22 03:02:27.913767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27e1cbe927d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название категории'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание категории'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_create', sa.DateTime(), nullable=False),
    sa.Column('to_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('store',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_create', sa.DateTime(), nullable=False),
    sa.Column('to_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unit',
    sa.Column('measure_type', sa.String(length=25), nullable=False, comment='Тип единицы измерения'),
    sa.Column('unit', sa.String(length=25), nullable=False, comment='Единица измерения'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_create', sa.DateTime(), nullable=False),
    sa.Column('to_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('name', sa.String(length=500), nullable=False, comment='Название продукта'),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_create', sa.DateTime(), nullable=False),
    sa.Column('to_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('purchase',
    sa.Column('product_id', sa.Integer(), nullable=False, comment='ID продукта'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='ID магазина'),
    sa.Column('purchase_date', sa.Date(), nullable=False, comment='Дата покупки'),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False, comment='Количество купленного товара'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Общая стоимость покупки'),
    sa.Column('regular_unit_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Обычная цена за единицу (без акции), если известна'),
    sa.Column('is_promo', sa.Boolean(), server_default='0', nullable=False, comment='Товар по акции или нет.'),
    sa.Column('promo_type', sa.String(length=32), nullable=True, comment='Тип акции: discount/multi_buy/loyalty/clearance/coupon/cashback'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Комментарий к покупке'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_create', sa.DateTime(), nullable=False),
    sa.Column('to_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    op.drop_table('product')
    op.drop_table('unit')
    op.drop_table('store')
    op.drop_table('category')
    # ### end Alembic commands ###
